// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGJ7cU8rs2LhBF-p87BsV1z95zWacG7AI',
    appId: '1:100409935355:web:ef048ccb0a9db64280b75e',
    messagingSenderId: '100409935355',
    projectId: 'attendance-fe355',
    authDomain: 'attendance-fe355.firebaseapp.com',
    storageBucket: 'attendance-fe355.firebasestorage.app',
    measurementId: 'G-CW0JSWDXLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtdzMOWCmKY5ef_pamir40ZsfI4cf3GEk',
    appId: '1:100409935355:android:540589e28167bf9d80b75e',
    messagingSenderId: '100409935355',
    projectId: 'attendance-fe355',
    storageBucket: 'attendance-fe355.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDliJTQP4aL8KgRLuxmM7DvcVp2GRmrNxU',
    appId: '1:100409935355:ios:12a7bbaafdf3cf8b80b75e',
    messagingSenderId: '100409935355',
    projectId: 'attendance-fe355',
    storageBucket: 'attendance-fe355.firebasestorage.app',
    iosBundleId: 'com.example.attendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDliJTQP4aL8KgRLuxmM7DvcVp2GRmrNxU',
    appId: '1:100409935355:ios:12a7bbaafdf3cf8b80b75e',
    messagingSenderId: '100409935355',
    projectId: 'attendance-fe355',
    storageBucket: 'attendance-fe355.firebasestorage.app',
    iosBundleId: 'com.example.attendance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGJ7cU8rs2LhBF-p87BsV1z95zWacG7AI',
    appId: '1:100409935355:web:07bea6ebd629b6fc80b75e',
    messagingSenderId: '100409935355',
    projectId: 'attendance-fe355',
    authDomain: 'attendance-fe355.firebaseapp.com',
    storageBucket: 'attendance-fe355.firebasestorage.app',
    measurementId: 'G-9SX30J8T4L',
  );
}
